[pytest]
DJANGO_SETTINGS_MODULE = core.settings
pythonpath = .
testpaths = tests
python_files = tests.py test_*.py *_tests.py
addopts = --reuse-db --strict-markers
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
norecursedirs = .drafts .git venv venv_old
