# Generated by Django 6.0.1 on 2026-02-21 06:59

import storage.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID файла')),
                ('file', models.FileField(upload_to=storage.models.user_directory_path, verbose_name='Файл на диске')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('size', models.PositiveBigIntegerField(blank=True, default=0, verbose_name='Размер (байт)')),
                ('mimetype', models.CharField(blank=True, max_length=100, verbose_name='Тип контента')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('special_link_token', models.CharField(blank=True, default=None, max_length=64, null=True, unique=True, verbose_name='Токен внешней ссылки')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Количество скачиваний')),
                ('last_download_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего скачивания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ('-created_at',),
            },
        ),
    ]
