# Generated by Django 6.0.1 on 2026-02-24 05:56

import django.contrib.auth.password_validation
import django.core.validators
import users.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID пользователя')),
                ('password', models.CharField(max_length=128, validators=[django.contrib.auth.password_validation.validate_password])),
                ('username', models.CharField(error_messages={'unique': 'Пользователь с таким логином уже существует.'}, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Логин должен быть от 4 до 20 символов, начинаться с буквы и содержать только латиницу и цифры.', regex='^[a-zA-Z][a-zA-Z0-9]{3,19}$')], verbose_name='Логин')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Полное имя')),
                ('storage_path', models.CharField(blank=True, max_length=500, verbose_name='Путь к хранилищу')),
                ('email', models.EmailField(error_messages={'unique': 'Пользователь с такой электронной почтой уже существует.'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Введите корректный формат email')], verbose_name='Электронная почта')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Статус администратора')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('-date_joined',),
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
